# Generated by Django 3.1.5 on 2021-01-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='created',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='content',
            new_name='details',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='due_date',
        ),
    ]
