# Generated by Django 3.1.5 on 2021-01-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_auto_20210107_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.DeleteModel(
            name='details',
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='details',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-01-07'),
        ),
    ]
